services:
    app:
        build:
            context: ./relieveme-back
            dockerfile: ./relieveme-back/Dockerfile
        networks:
            - net
        links:
            - nginx
            - redis
            - postgres
        depends_on:
            - nginx
            - redis
            - postgres
        restart: unless-stopped
        environment:
            APPLICATION_ENV: development
        volumes:
            - .:/var/www/html/
    nginx:
        image: nginx:1.19-alpine
        restart: unless-stopped
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./relieveme-back:/var/www/html/relieveme-back
            - ./docker/nginx-logs:/var/log/nginx/
        networks:
            - net
        ports:
            - 80:80
        depends_on:
            - redis
            - postgres
        networks:
            - net
        restart: unless-stopped
    redis:
        image: redis:6-alpine
        ports:
            - 6379:6379
        networks:
            - net
        restart: unless-stopped
    postgres:
        image: postgres:13.2-alpine
        restart: unless-stopped
        ports:
            - 5432:5432
        networks:
            - net
        environment:
            POSTGRES_USER: relieveme
            POSTGRES_PASSWORD: relieveme
            POSTGRES_DB: relieveme
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - postgres:/var/lib/postgresql/data/pgdata
networks:
    net:
        driver: bridge
volumes:
    postgres:
        driver: local
