#!/usr/bin/env bash
LOCAL=$PWD
PARENT="$(dirname "$LOCAL")"
SSH=$HOME
docker run -ti --rm -p 8080:8080 -p 9501:9501 -v ${PARENT}:/var/www -v ${SSH}/.ssh:/root/.ssh -w /var/www/relieveme brossquad/php-dev:8.0-1.0.5 $@

