#!/usr/bin/env bash
LOCAL=$PWD
PARENT="$(dirname "$LOCAL")"
SSH=$HOME
docker run -ti --user "$(id -u):$(id -g)" --network relieveme_net --rm -p 8080:8080 -p 9501:9501 -v ${PARENT}:/var/www -v ${SSH}/.ssh:/.ssh -w /var/www/relieveme-back relieveme_app:latest $@

